### PR TITLE
allure reports

### PR DESCRIPTION
**Pull request by miniTeckel**
Add new workflow for Allure reports. In order to work it requires a branch with name "gh-pages"  and GitHub pages configured to use it. There is an example for allure reports in my repository: https://miniteckel.github.io/TestAutomationCourse-python-api-project/1/

### CODE REVIEW

**Comment by BurhanH** [comment]
Nice! How can I check those reports? @miniTeckel 
Could you share any samples?
Thanks

**Comment by miniTeckel** [comment]
You can see the report in my fork: https://miniteckel.github.io/TestAutomationCourse-python-api-project/1/#suites

**Comment by BurhanH** [comment]
But it's your own allure server. Can we use it for our repository?
How we can share those results with anyone?
If someone will clone this repository does he/she need to configure their own allure server?
@miniTeckel

**Comment by BurhanH** [comment]
Oh! I see it uses GitHub pages to publish allure reports.

**Review by BurhanH — APPROVED** [review]

**Comment by BurhanH** [comment]
Code is merged. Do I need to change something in the current repository in order to see/get the allure report? @miniTeckel

**Comment by BurhanH** [comment]
I got it - https://burhanh.github.io/TestAutomationCourse-python-api-project/1/

**Pull request merged**
